### ISSUE TITLE
Support for "IcedCoffeeScript" ?

### ISSUE THREAD

**Issue by lazytyper** [jadejs/jade-filters#20]
I've just discovered "IcedCoffeeScript" which is "a superset of CoffeeScript".

It looks very interesting. It supports `await` and `defer`, which makes asynchronous programming easier.

A documentation is here: http://maxtaco.github.io/coffee-script/

Maybe it's worth to add a filter, like `:icedcoffee` for it. `doublerebel` has also added gulp support for it:
https://github.com/doublerebel/gulp-iced-coffee

**Comment by ForbesLindesay** [comment]
See https://pugjs.org/language/filters.html We use JSTransformers, so all you need to do is install an appropriate adapter: https://www.npmjs.com/browse/keyword/jstransformer

If there isn't one for your language yet you can either open an issue on https://github.com/jstransformers/jstransformer to request one, or better yet, add one yourself.
